default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: shoutr_development
  pool: 5
  timeout: 5000

test:
  <<: *default
  database: shoutr_test
  pool: 5
  timeout: 5000

production:
  <<: *default
  database: shoutr_production
  pool: 5
  timeout: 5000
